version: "3"
services:
  mongo_server:
    image: mongo
    ports:
      - "27017:27017"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    depends_on:
      - client
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules/
      - ./client:/app
    ports:
      - "5173:5173"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules/
      - ./server:/app
    ports:
      - "3001:3001"
